### PR TITLE
New E5 Models in Registry

### PR DESCRIPTION
**Pull request by OwenElliottDev**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature - new E5 Models

* **What is the current behavior?** (You can also link to an open issue here)
E5 V2 and multilingual E5 models are not in the registry

* **What is the new behavior (if this is a feature change)?**
E5 V2 and multilingual E5 models are now in the registry

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Have unit tests been run against this PR?** (Has there also been any additional testing?)
All unit tests pass. Indexes created with the new models work as expected.

* **Related documentation changes** (link commit/PR here)
https://github.com/marqo-ai/marqodocs/pull/111

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Review by pandu-k — COMMENTED** [review]
Thanks Li! Do we need a test ensuring that we can create a new index with one of the new model types, as expected, and then add a doc and search?

**Comment by OwenElliottDev** [comment]
@pandu-k is there anything pending on this?

**Comment by pandu-k** [comment]
Hi Owen, thanks for this!
- Have some of these models been manually end-to-end (as part of a Marqo index) tested for performance (recall + latency). Eyeballing is fine for now at this stage. 
- Do we need a test ensuring that we can create a new index with one of the new model types, as expected, and then add a doc and search? @wanliAlex do you have any examples of these types of tests? 
- It would be good for @wanliAlex to also have a review

**Comment by OwenElliottDev** [comment]
> Hi Owen, thanks for this!
> 
> * Have some of these models been manually end-to-end (as part of a Marqo index) tested for performance (recall + latency). Eyeballing is fine for now at this stage.

I tested all of these models locally with a dev build of Marqo before I raised this PR. I haven't benchmarked them though our simple wiki demo is using e5-base-v2 https://demo.marqo.ai/?q=what+is+isaac+newton+known+for&index=simplewiki

**Review by wanliAlex — APPROVED** [review]

**Pull request merged**
