### PR TITLE
Visual search update release

### PR DESCRIPTION
**Pull request by jn2clark**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
It introduces:
1) additional heuristic methods for the image preprocessing via chunking (or patching) (see https://marqo.pages.dev/Preprocessing/Images/)
2) additional models for the image preprocessing via chunking (or patching) (see https://marqo.pages.dev/Preprocessing/Images/)
3) a text-image based reranker that allows reranking of images based on an open-vocabulary model (owl-vit) 
4) An example script and streamlit app to demonstrate the new functionality
5) tests for the new functionality

* **What is the current behavior?** (You can also link to an open issue here)
1) Currently we have two methods for image based pre-processing. A simple grid based heuristic and a faster-rcnn based model from pytorch (trained on mscoco)
2) There is no option for open-vocabulary localization or re-ranking based on images

* **What is the new behavior (if this is a feature change)?**
1) The new behavior is there are more options to select a model for pre-proessing. A yolox based onnx model trained on LVIS is added, models based on determining salient regions of images from attention maps is included (based on DINO)
2) There is a new heuristic based model which uses overlapping boxes instead of a non-overlapping grid.
3) Re-ranking of images from text based queries is possible

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Have unit tests been run against this PR?** (Has there also been any additional testing?)
Yes

* **Related Python client changes** (link commit/PR here)
None

* **Related documentation changes** (link commit/PR here)
To be included

* **Other information**:
api tests are here 
https://github.com/marqo-ai/marqo-api-tests/tree/visual_search_update
Manual testing end-to-end via the demo has been performed as well

This is an update to the previous one. Mainline was remerged into the branch.
https://github.com/marqo-ai/marqo/pull/205

* **Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by jn2clark** [comment]
Previous PR https://github.com/marqo-ai/marqo/pull/205

**Comment by jn2clark** [comment]
image

**Comment by pandu-k** [comment]
Strange git diff between this PR and mainline .github/workflows files. Manually checking diffs between files:
- arm64_local_os: identical
- cuda DIND: identical
- cuda OS: identical
- local OS: identical
- s2search backend: identical
- unit tests

**Comment by jn2clark** [comment]
Sorry @pandu-k . I thought I had avoided those weird things be merging mainline back in.

**Comment by pandu-k** [comment]
> Sorry @pandu-k . I thought I had avoided those weird things be merging mainline back in.

You couldn't have helped it, these are changes from the generic models feature

**Review by pandu-k — APPROVED** [review]

**Pull request merged**
