### PR TITLE
added jupyter file for ClothingCLI example

### PR DESCRIPTION
**Pull request by vandit98**
* ** This pr is with respect to issue #96**  It includes Documentation of python scripts into jupyter 
 notebook.

* **What is the current behavior?** (You can also link to an open issue here)
https://github.com/marqo-ai/marqo/issues/96

### CODE REVIEW

**Comment by vandit98** [comment]
Above is an example. Please assign this issue to me. I've already ready with the changes, for other examples  just have to push the pull request.

**Comment by jn2clark** [comment]
Thanks @vandit98! Looks good so far, would you be able to show what the output is when you run the notebook `main()` function is?

**Comment by vandit98** [comment]
yes i will add it

**Comment by vandit98** [comment]
hey
I have added the jupyter file for all examples.

**Comment by jn2clark** [comment]
Thanks @vandit98 ! Would you be able to test the notebooks? for example, I am not sure this code should be added to a notebook https://github.com/marqo-ai/marqo/blob/e78ec142dbfc0983a824301f527d59a27a472e2c/examples/ClothingStreamlit/stream_lit_marqo_demo.ipynb since it is an application. I suggest re-writing it so the application 'runs' inside the notebook instead of streamlit. alternatively, exclude this example from the PR

**Comment by vandit98** [comment]
hey @jn2clark 
I have excluded the example from the pull request.

**Pull request closed without merging**
