### PR TITLE
[feature]Logger fix

### PR DESCRIPTION
**Pull request by wanliAlex**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
we move most log information in `tensor_search` to `debug` level. We will have a cleaner indexing and search log at default "INFO" level.

* **What is the current behavior?** (You can also link to an open issue here)
there are too much information in "INFO" logger level

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Have unit tests been run against this PR?** (Has there also been any additional testing?)
NO

* **Related Python client changes** (link commit/PR here)
No

* **Related documentation changes** (link commit/PR here)
NO

* **Other information**:
check here for a more detailed explanation. https://github.com/marqo-ai/marqo/issues/359#issuecomment-1449177743

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by wanliAlex** [comment]
The log in Marqo docker when we `add_document` several times and do a search.

`-e MARQO_LOG_LEVEL = 'warning'`
image

`-e MARQO_LOG_LEVEL = 'info'` or  **PASSING NOTHING**
image


`-e MARQO_LOG_LEVEL = 'debug'`
image

**Review by pandu-k — APPROVED** [review]

**Comment by pandu-k** [comment]
Unit tests running: https://github.com/marqo-ai/marqo/actions/runs/4309472379

**Comment by wanliAlex** [comment]
@Jeadie @VitusAcabado for cloud team.

**Comment by VitusAcabado** [comment]
awesome! Thanks @wanliAlex!

**Pull request merged**
