### PR TITLE
Absolute model cache paths

### PR DESCRIPTION
**Pull request by pandu-k**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix

* **What is the current behavior?** (You can also link to an open issue here)
the model cache dir is relative, and therefore unpredictable. This can lead to the interpreter not being able to load a model if the CWD changes. 

* **What is the new behavior (if this is a feature change)?**
The model cache directories are now consistent and relative to the Marqo root. 

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Have unit tests been run against this PR?** (Has there also been any additional testing?)
In progress

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by pandu-k** [comment]
Unit tests running: https://github.com/marqo-ai/marqo/actions/runs/4380985145

**Comment by pandu-k** [comment]
API tests: https://github.com/marqo-ai/marqo/actions/runs/4381003898

**Review by wanliAlex — APPROVED** [review]

**Comment by pandu-k** [comment]
Tests:
- Unit: https://github.com/marqo-ai/marqo/actions/runs/4381804354
- API: https://github.com/marqo-ai/marqo/actions/runs/4381803070

**Comment by pandu-k** [comment]
Rerunning unit tests: https://github.com/marqo-ai/marqo/actions/runs/4382008075

**Review by wanliAlex — APPROVED** [review]

**Pull request merged**
